### ISSUE TITLE
Items with position: sticky break the virtual list

### ISSUE THREAD

**Issue by frabarz** [oleggrishechkin/react-viewport-list#1]
If the list has headers items styled with `position: sticky`, the list breaks.
This is caused due the use of `.getBoundingClientRect()` on the first element of the list, whose top value doesn't change when positioned as sticky, causing the internals to not recognize the scrolling and preventing the update of the list items.
To try to make it work, I passed the indexes of the sticky items and made the component ignore them when passing the innerRef to the child function, and also made it render these item at all times to prevent the stickied item from disappearing if the list is too long.
My patched version of the component is currently on [this repo](https://github.com/frabarz/blueprintjs-select-virtual/blob/ae7e16a515793b64eb56561e5e0fa1cd74c445b6/src/components/ViewportList.jsx#L150-L169), but I'm not very confident on the quality of the code, so I decided to make this issue instead of a PR.

BTW, this is the first react-virtual-list component I find that can handle undetermined heights correctly. Great job.

**Comment by oleggrishechkin** [comment]
Thanks for your feedback.
This list has many limitations, `absolute`, `fixed` and `sticky` positioning work incorrect.
But it's not a virtual list, its a virtual part of the list... so you can use `ViewPortList` component for not sticky items like this:

```javascript
<ScrollContainer>
    <StickyItem>
    <ViewPortList>
        {...}
    </ViewPortList>
    <StickyItem>
    <ViewPortList>
        {...}
    </ViewPortList>
...
</ScrollContainer>
```
If you only has sticky header this solution should work

**Comment by frabarz** [comment]
It's a lot ~less hacky~ more elegant than my solution, thanks!
My only concern is that, since the component renders enough list items to fill a screen height (twice, if not fixed), there's still a lot of items being rendered. In my test I saw 1200 children nodes for the ScrollContainer. But the list I'm working with won't handle more than 500 elements, and since it's still fast, won't be much of a problem.

**Comment by oleggrishechkin** [comment]
Do you set **itemMinHeight** prop? by default is `1`, and list render thousands items, for example if **itemMinHeight** is `20`, list render `~100` elements for `1000px` window. I work on optimize this, but this list can't render only items in view port like true virtual list with fixed items height.

(I fill screen height twice for prevent scroll lagging when items shift/unshift while scrolling without setting `scrollTop`)

**Comment by oleggrishechkin** [comment]
issue with position: sticky solved
