### ISSUE TITLE
Why forcing to specify itemMinSize when 0 always works?

### ISSUE THREAD

**Issue by lcswillems** [oleggrishechkin/react-viewport-list#19]
Hi Oleg,

Thanks a lot for your package!! Really easy to use!

I was wondering: the itemMinSize property is required but when I set it to 0 it works perfectly. Why having this property and why requiring it?

**Comment by oleggrishechkin** [comment]
Hi,
itemMinSize is like estimated size. If you set it to 0 the component will not create additional space for scrollbar. So for more "real" behaviour you must set itemMinSize to some real value if it's possible (I guess for most cases it's possible).

The main rule - real item size should't be less than itemMinSize, it may cause unexpected scroll behavour.

**Comment by lcswillems** [comment]
Thanks for your answer!

What do you mean by "If you set it to 0 the component will not create additional space for scrollbar"? In my case, set it to 0 and still have the scrollbar visible

**Comment by oleggrishechkin** [comment]
For example - you have list of 5 items. Sizes - [10px, 20px, 50px, 10px, 15px]. In viewport only first two items (10px and 20px).

Scroll container `scrollHeight` is only 30px = 10 + 20 + 0 + 0 + 0 if you use `itemMinSize={0}`.
But if you don't use virtualization the `scrollHeight` is 10 + 20 + 50 + 10 + 15 = 105px.

Otherwise, you can use `itemMinSize={10}`. And now the `scrollHegiht` is 10 + 20 + 10 + 10 + 10 = 60px.

60px is closer to the real value (105px). Scroll drag'n'drop will be more effectively. Users will see "bigger" scroll bar, that means more items is "hidden" from viewport - it's better for UX.

**Comment by lcswillems** [comment]
Thanks for the explanations! I now see what you mean! What is weird is that I set the itemMinSize to 0 but the scroll bar is of correct size... I might have done something wrong. I am going to investigate

**Comment by oleggrishechkin** [comment]
Maybe full list was rendered and then virtualized. So all item sizes was cached.

I'll check what exactly happened when itemMinSize is zero.

**Comment by oleggrishechkin** [comment]
@lcswillems I cheched, if you specify itemMinSize to 0 it may cause unexpected behaviour - some times component will be broken, some times component will render full list (all items). I think this should be clarified in docs and itemMinSize=0 should be guarded to not broke the code.

Thanks for your feedback

**Comment by lcswillems** [comment]
Thanks for having checked! I think it should be made clear about in which cases it is okay to set it to 0. In my case, it seems to work great with 0

**Comment by lcswillems** [comment]
Also this line in the README:

"Created for dynamic item height/width (if you don't know item size)"

is a bit mislead as you say that the itemMinSize should be specified to get something that works, so I should know something about the height/width

**Comment by oleggrishechkin** [comment]
Sometimes you don't know item size before item was rendered - a texts or images for example. But you know how item looks (you know item layout) - `padding`, `min-height` in css. So you can use it for itemMinSize.

**Comment by lcswillems** [comment]
But you say that if I don't use itemMinSize react-viewport-list might not display items or scrollbar correctly right? In this case, I need to know something about the height/width if I want it to work correctly

**Comment by oleggrishechkin** [comment]
Yes, you should know something. With no data react-viewport list cant predict anything.
