### ISSUE TITLE
Virtual list doesn't work when scrollToIndex = 0

### ISSUE THREAD

**Issue by frabarz** [oleggrishechkin/react-viewport-list#2]
I'm passing a value to `scrollToIndex` from the first render, since I'm giving the user control to move through the list with the keyboard, but at the beginning, when this value is 0, the library didn't update the list items on scroll. After moving once with the keyboard, the library starts working as intended.  
Checking the code, I found that when this value is 0, the `frame` function [gets stuck on this line](https://github.com/oleggrishechkin/react-viewport-list/blob/master/src/index.js#L79).  
At the beginning the value of `variables.current.scrolledToIndex` is -1, the comparison gives `true`, but then since `scrollToIndex` is 0 and the initial value of `startIndex` is 1, there's no point where the `variables.current.scrolledToIndex` variable gets updated, and the function returns.

To workaround this, I prevented the value I'm passing to `scrollToIndex` to be 0. The virtual list works, but it won't scroll to the first item when navigating with the keyboard.

**Comment by oleggrishechkin** [comment]
Thanks for your feedback.

This problem fixed in version `1.3.2`. Now scroll should work correctly.
