### ISSUE TITLE
scroll window

### ISSUE THREAD

**Issue by arb195** [oleggrishechkin/react-viewport-list#28]
hi 👋🏻
when I scroll the window, I want the viewport list to start scrolling that means synchronize both

**Comment by oleggrishechkin** [comment]
Hi,
I don't understand.

ViewportList is just a fragment with items. If you want to sync some scroll container with body scroll you can do it manually.

If you have a body as a scroll container you can just omit viewportRef prop

**Comment by arb195** [comment]
exactly i want when scrolling the body scroll my viewport list.
but when remove viewportRef render all of the data on page.
