### ISSUE TITLE
Wrong indexes onViewportIndexesChange 

### ISSUE THREAD

**Issue by Barruchou** [oleggrishechkin/react-viewport-list#29]
Hi,

Either I don't understand the behavior or there is a bug.
With "onViewportIndexesChange" the starting index does not coincide with what is actually displayed.
Here it should be 0-1 then 1-2 then 2-3 etc.
![indexes-issue](https://user-images.githubusercontent.com/38187278/190994872-c236af26-c379-49c0-8f14-6d077844478c.gif)

Thanks in advance

**Comment by Barruchou** [comment]
Thanks for the reply, I put the direct parent of the list as shown in the documentation

**Comment by Barruchou** [comment]
Closed ?

**Comment by oleggrishechkin** [comment]
I thought that all is ok, this is still reproduce?

**Comment by Barruchou** [comment]
I was using the wrong container, my bad.

Thanks for https://github.com/oleggrishechkin/react-viewport-list/releases/tag/6.0.0

I do not use `onViewportIndexesChange` anymore.

It's clearer with the new doc.
