### ISSUE TITLE
scrollToIndex is only scrolling when the index is for an item that is already in the viewport

### ISSUE THREAD

**Issue by Pastromhaug** [oleggrishechkin/react-viewport-list#32]
It seems like `scrollToIndex` only works if the index passed in is for an item that is already in the viewport. In my use case, I have a really long list with a navigation sidebar that allows you to click and scroll to any item in the list.

I was wondering if this is the intended behavior, or if I'm doing something wrong. Thanks!

**Comment by Pastromhaug** [comment]
Just tried updating to 6.0.2, but seeing the same behavior.

**Comment by oleggrishechkin** [comment]
Hi, thanks!
I checked scrollToIndex and found where the issue is.

(scrollToIndex should set rendered indexes but this doesn't happened)

**Comment by oleggrishechkin** [comment]
@Pastromhaug should be fixed in 6.0.3

**Comment by Pastromhaug** [comment]
Upgrading to 6.0.3 fixed the issue! Thanks for the quick fix. I'm enjoying this library
