### ISSUE TITLE
Wrong peerDependency version

### ISSUE THREAD

**Issue by bjornhenriksson** [oleggrishechkin/react-viewport-list#34]
Hey! Thanks for working on this awesome package. It looks to me however that the peerDependency version required for React is wrong? The code seems to rely on the ability to use `react/jsx-runtime` which was first added in `react@17`: https://github.com/facebook/react/releases/tag/v17.0.0. 

All the best,
Björn

**Comment by oleggrishechkin** [comment]
Hi, thanks for your feedback. I missed it. Seems to be we can use legacy jsx runtime to support react >16.8.

Do you know some cons for use legacy jsx runtime in library instead of new jsx-transform?

**Comment by oleggrishechkin** [comment]
I updated react in peerDependencies to 17+. This library work with new jsx-transform a long time, so I keep this behaviour.
Let me know if you need to react 16 support

**Comment by bjornhenriksson** [comment]
@oleggrishechkin thanks for the quick reply! Sadly I can't be of more help because I don't know that much. But the project I was meant to use this for will just have to bump to 17! :D
