### ISSUE TITLE
When using react-viewport-list, children not being rendered in test.

### ISSUE THREAD

**Issue by nikithb** [oleggrishechkin/react-viewport-list#38]
I'm using Jest and React Testing Library. Windowing works fine in browser, but list items are not being rendered in tests.
Test was able to find only one item of whole list, all other items were not being rendered.

How can I mock this ViewPortList, so that whole list gets rendered at once?.

**Comment by oleggrishechkin** [comment]
Hi, @nikithb 

react-viewport-list uses requestAnimationFrame - you can wait for it before `expect`.

If waiting not working:

I don't know how Jest mock window and DOM itself. getBoundingClientRect should work for correct virtualisation. So, you can try to mock this method.

**Comment by oleggrishechkin** [comment]
It's just work. 

But maybe we can use better solutions with virtualization by mocking sizes of viewportRef and items.
