### ISSUE TITLE
Spacer Element Types

### ISSUE THREAD

**Issue by blongstreth** [oleggrishechkin/react-viewport-list#42]
Any chance you can look into allowing for a different element type for the hidden spacer elements?  The reason I ask is because I would like to use this component for an html `table`.  The `tr` is the permitted content element for `tbody`.  Please see [tbody](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tbody).

**Comment by oleggrishechkin** [comment]
Hi, @blongstreth. Sure. I did't see any limitations to add this feature. I think it can be a "spacer" prop

**Comment by oleggrishechkin** [comment]
@blongstreth I published 6.1.0 just now with this feature. Try to use `spacerElement="tr"`

**Comment by blongstreth** [comment]
Thank you!  I will check it out when I get a change!

**Comment by oleggrishechkin** [comment]
@blongstreth Did you try it? Can I close this issue?

**Comment by blongstreth** [comment]
@oleggrishechkin sorry for the delay.  I did review your changes and I think they will work.  I will try and test them when I get some time.

**Comment by oleggrishechkin** [comment]
Looks like issue is resolved. Closed.
