### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by ChristophP** [oleggrishechkin/react-viewport-list#45]
I was fighting with react-window for a while until I found `react-viewport-list`.
It was easy to install and worked exactly as I expected without inserting unwanted DOM elements or requiring me to specify the height and item size.

Thanks for making this

**Comment by ChristophP** [comment]
Yes that was exactly my experience. It felt very difficult to work with, with dynamic heights and so. `react-viewport-list` made this super simple. :-)

**Comment by inkiltie** [comment]
Top notch library! My hundred thousands line lists are now flying. Thanks.
