### ISSUE TITLE
New items added to bottom of list. After refresh, appeared first.

### ISSUE THREAD

**Issue by tomchify** [oleggrishechkin/react-viewport-list#46]
Hi, thank you for this wonderful library. I'm loving the performance. 

I'm rendering a ViewportList like this:
```
<ViewportList
        ref={listRef}
        viewportRef={ref}
        items={**items**}
        initialIndex={0}
        initialOffset={savedScroll}
      >
```

**items** is an array of objects in reverse-chronilogical order. They appear in correct order on first load.

When, a new item is pushed to the front of the items array (It's powered by a firebase query snapshot update), the new item appears in the ViewportList at the bottom of the list, which is unexpected. 

After a refresh, the new item appears at the top, as expected. 

Is there a way to handle inserting elements to the beginning of the items list, and having it refresh correctly?

Thanks

**Comment by oleggrishechkin** [comment]
Hi, @tomchify 

Do you use a `key` prop for item? In your case you must use a key and it should be unique like item's id.

**Comment by tomchify** [comment]
Thanks for the quick response. Yes, I have a key prop like this:

```
<ViewportList
        ref={listRef}
        viewportRef={ref}
        items={items}
        initialIndex={0}
        initialOffset={savedScroll}
      >
        {(item) => (
          <div key={item.objectID} className="item">
            <AICompactTaskListCell task={item} />
          </div>
        )}
      </ViewportList>
```

**Comment by oleggrishechkin** [comment]
I implemented your case with shifting items to the items array. Works well. Are you sure that `items` correctly sorded when you add new item?

**Comment by tomchify** [comment]
🙈 yes, items just needed a sorting. Should have gone to sleep. Sorry to bug you. Thanks for the help. I welcome my AI replacements lol.

**Comment by oleggrishechkin** [comment]
This is not react-viewport-list related issue. Closed
