### ISSUE TITLE
Scroll to bottom on initial render

### ISSUE THREAD

**Issue by wong2** [oleggrishechkin/react-viewport-list#60]
Currently, the behavior is the list stays at top on initial render, I'd like it to be at bottom. 
I've tried `initialIndex`, `initialAlignToTop` with no luck.

**Comment by oleggrishechkin** [comment]
Hi, @wong2 
I created a fork of demo with a scroll to bottom (via ininitalIndex) https://codesandbox.io/s/react-viewport-list-forked-7ktgdc?file=/src/App.js

Could you provide reproduction?
Maybe your scroll container (viewportRef) is wrong or automatic scroll container recognition (if you not provide viewportRef at all) failed

**Comment by wong2** [comment]
Thanks! it works now
