### ISSUE TITLE
flew wrap not work

### ISSUE THREAD

**Issue by MaherUnlocker** [oleggrishechkin/react-viewport-list#61]
i have row include col-6   classname 
but it always show list not card side card i want  like this  picture 

![image](https://user-images.githubusercontent.com/30791819/226877247-10ed34ea-b855-43b8-bc16-15bf5ce5316f.png)

**Comment by oleggrishechkin** [comment]
Hi, @MaherUnlocker 
Could you clarify what you mean?

As I right understand you, you want to render two column grid, but rendered only one column/list?

First, you should not use ViewportList this way. Each item should be a "row". Yes, maybe ViewportList show you a correct grid, but it can't work correctly with two or more column layout.

The best way is group you items in chunks "rows" like [ [items[0],items[1]], [items[2], ... ], ...] and render it as a list where each row is a two cards
