### ISSUE TITLE
Is infinite scroll pagination supported?

### ISSUE THREAD

**Issue by impzero** [oleggrishechkin/react-viewport-list#62]
Hi, I've just found this library and I am trying to integrate it in my infinite scroll page (using Capacitor with `<IonPage />`, i don't know if that is relevant 😁 ). The `items` prop is expected to increase as the user scrolls more and more into the view since I am fetching more and more data from the server. 
Currently as I fetch more and more data (I merge all the pages I get from the server in one array) and I pass it to the `items` prop. But for same reason the component doesn't even iterate through my array. I confirmed and the array is not empty.

Is such behavior supposed to work with this component, or is my approach of passing the total data fetched to the component wrong (should I be passing only the current page?)

Right now I can't reproduce this, but I will be thankful if I get your feedback!

**Comment by oleggrishechkin** [comment]
Hi, @impzero 
I created a sandbox with infinite list:
https://codesandbox.io/s/react-viewport-list-forked-fmh394?file=/src/App.js

I not understand your case, but if new elements not render but items is correct it can be a problem with mutation/order or (if you render a really huge list like 1kk items) you can exceed a maximum possible block height (it's about 16kk px). (in case with a massibe lists you can use `withCache={false}` props and `itemSize={1}` or other small value to not exceed max height and `itemMargin={0}`

Maybe I can say more reasons if you provide some reproduction or part of your code.
