### ISSUE TITLE
Scroll to position

### ISSUE THREAD

**Issue by MOHIDQ** [oleggrishechkin/react-viewport-list#63]
I’m using react router and was wondering is there a way in that when a user goes back to a route it will keep the same scroll position? I understand there is a scroll to index and scroll to position using initial offset but I’m having trouble understanding how to calculate the correct offset in this scenario to get the screen to the correct previous scroll position. 

Using the following (where variable y i'm storing the previous scrollTop position of the scrollable div) doesn't scroll back to the correct position:
listRef.current.scrollToIndex({
                index: 0,
                offset: y
});

**Comment by oleggrishechkin** [comment]
Hi, @MOHIDQ.

You soultion with `scrollTop` can work correctly only for fixed item height.
The best solution at this moment is manually compute `index` and `offset` on item's click (if you open some "item view" from "list" by clicking at item). `offset` should be the difference between viewport `getBoundingClientRect().top` and clicked item `getBoundingClientRect().top` (it will be negative for most cases). `offset` is just a value which will be added to scrollTop (or scrollLeft) after scroll to element by index.

I think I can add `getScrollPosition()` method in the next minor release to get `index` and `offset` for scroll restoration without pain.

**Comment by MOHIDQ** [comment]
Thanks, that works very well! didn't think about using getBoundingClientRect().top for the clicked on element! Definitely making adding a method to capture the current scroll position would be great, but this solution works for now

**Comment by oleggrishechkin** [comment]
@MOHIDQ Anyway I added `getScrollPosition` method in 7.1.0 release. You can use it for computing `index` and `offset` for `initialIndex`/`initialOffset` or `scrollToIndex` on component unmount/route change/scroll etc.

something like this:

```
// save last scroll postiion somewhere. It can be a sesstion storage or some variable outside your component for example. 
lastScrollPosition = viewportListRef.current.getScrollPosition();

// now we can use index and offset in out ViewportList for scroll restoration
<ViewportList>
    ...
    initialIndex={lastScrollPosition.index}
    initialOffset={lastScrollPosition.offset}
</VIewportList>
```
