### ISSUE TITLE
remove spacer in list

### ISSUE THREAD

**Issue by misterbeedev** [oleggrishechkin/react-viewport-list#65]
how to remove renderspacer (first and last elements) in list

**Comment by oleggrishechkin** [comment]
You can't remove spacers because this is a base part of this library. 

Why you want to delete spacers?

**Comment by bfan1256** [comment]
I'm tryign to use this with a tailwind grid, is there a way to start it as display none because the first div takes up the first space in the grid...

**Comment by oleggrishechkin** [comment]
> I'm tryign to use this with a tailwind grid, is there a way to start it as display none because the first div takes up the first space in the grid...

@bfan1256, you should use `renderSpacer` and add tailwind className to fill all columns (if your list is vertical). First div must have space. It represents offscreen items.

But I'm not recommend multicolumn grids/flex with wrap) for using with react-viewport-list - this one is unsupported.
