### ISSUE TITLE
Scroll X and Scroll Y and sticky rows and columns 

### ISSUE THREAD

**Issue by Arshad737** [oleggrishechkin/react-viewport-list#66]
does it support scroll in x and y axis at the same in the same list
also I keen to know if the package supports sticky rows and columns 
thanks in advance.

**Comment by oleggrishechkin** [comment]
Hi, @Arshad737 scroll in both axis at the same time not supported. You can create a list where each row will be ViewportList but I can't recommend you this way. Also you can't use sticky elements - one of the possible whays to use sticky is grouping like:

```
<Scrollable>
  <Sticky />
  <ViewportList />
  <Sticky/>
  <ViewportList />
```

If your case is a big data table I think it's better to use other library like react-window. It also will be more performant in this case.

**Comment by Arshad737** [comment]
I have a grid with sticky rows and columns, 
I have been using react-window for virtualization, but it doesn't work for the grids which have sticky columns because of position absolute.
I can work with y-scroll, but need columns to be virtualised

**Comment by oleggrishechkin** [comment]
Do you use native css `position: sticky;`? I don't know a virtualization library to support this. You should use js approach and react-virtualize and virtuoso support it.

If your columns have a fixed width and sticky rows are fixed too (I mean only some specific rows are sticky (maybe the first row) you can try to use solution described by me above:

Render vertical list before sticky row, render sticky row, render vertical list before next sticky row...
Each row is horizontal list too.
Not pretty solution, but this is what you can do to support css sticky.
