### ISSUE TITLE
Having trouble getting axis="x" to work

### ISSUE THREAD

**Issue by samuel-messing** [oleggrishechkin/react-viewport-list#75]
Hello! 

I continue to use this project and it has been working great for me. Today I have attempted to make my first horizontally scrolling list using `<ViewportList>`. To start, I just added `axis={"x"}`, and on reload it still scrolls vertically. I've looked through the docs and its unclear if there's something else that is needed to get it to work? Are there any specific conditions that the individual items need to meet for it to work?

For my use case, I specify the fixed size of the items, both their height and width (they're square images).

**Comment by oleggrishechkin** [comment]
Hi, @samuel-messing, 
Do you change styles of your scroll container? It should be something like `overflow-x: auto`.  So you need to change your styles to render elements horizontally.

ViewportList doesn't add any styles to container and axis="x" just change properties in calculation to "width"-like.

**Comment by oleggrishechkin** [comment]
@samuel-messing, you can check this [example](https://codesandbox.io/p/sandbox/react-viewport-list-axis-x-z8j6j4) with x-axis

**Comment by samuel-messing** [comment]
That worked! I also had accidentally specified `flex-direction: column`, changing that to `row` and `overflow-x: auto` worked for me. Thanks for the quick response!
