### ISSUE TITLE
justify-content: flex-end; hides the scroll bar.

### ISSUE THREAD

**Issue by Codename-404** [oleggrishechkin/react-viewport-list#77]
I was trying to make it so, the list starts from bottom of the container, and pushes the items top and once it goes beyond the container height, it starts scrolling.
Everything works expect when I add "justify-content: flex-end;" this to the css, it just doesn't show the scroll bar anymore.

You can try this in here: https://codesandbox.io/p/sandbox/react-viewport-list-forked-txvfgg?file=%2Fsrc%2FApp.js%3A6%2C31
that's the same code base, just added justify-content: flex-end; on the list class on app.css and updated the number of items, and it just stops showing the scroll bar.

Can you please help me with this? Looking forward to hearing from you.
Thank you ~

**Comment by oleggrishechkin** [comment]
Hi, @Codename-404 . `justyfy-content: flex-end` can be a bad case for scroll containers even without virtualization. I think you can try to wrap your scroll container into container with `justyfy-content: flex-end` if you want to render items starts form a bottom of some block - [see example](https://codesandbox.io/p/sandbox/react-viewport-list-forked-4mqmp4?file=%2Fsrc%2FApp.js%3A6%2C30)

**Comment by Codename-404** [comment]
Ah, it works, and Thank you very much for the tip!
Awesome plugin by the way ~
