### ISSUE TITLE
Styling is breaking if used in material ui table

### ISSUE THREAD

**Issue by sagarreddy-gfk** [oleggrishechkin/react-viewport-list#78]
I have a material ui table which renders 1000+ of rows and when I am placing scroll container div just after <tbody> styling for <tr> and <td> is breaking. Is there a way to handle when it comes to implementing in material ui table thereby ensuring that styling is not breaking. I also tried by changing div element display property as table-row. but still we are not getting default table styling.
And if I make <tbody> as scroll container then only row is rendering.

**Comment by oleggrishechkin** [comment]
Hi, @sagarreddy-gfk . If materula ui/or any other ui libarary) uses table layout you need to use `renderSpacer` to render div's as tr to work with table layout.

```
renderSpacer={({ ref, style }) => <tr ref={ref} style={style} />}
```

Your items should be table rows

**Comment by sagarreddy-gfk** [comment]
Thanks @oleggrishechkin !
