### ISSUE TITLE
Offset option for 'scrollToIndex'

### ISSUE THREAD

**Issue by matiasFont** [oleggrishechkin/react-viewport-list#9]
Is it possible to add a pixel offset with scrollToIndex?

I have problems with some fixed elements on the top of my viewport.

**Comment by oleggrishechkin** [comment]
Hi, which problems?

**Comment by oleggrishechkin** [comment]
May be, you can try this:

```
....scrollToIndex(...);
setTimeout(() => {
    scrollNode.scrollTop+= offset;
}, <more than 0>);
```

or use requestAnimationFrame instead of setTimeout

**Comment by oleggrishechkin** [comment]
Also, you can pass options to `alignTop` something like { block: 'center' }, element will be aligned to the center of viewport (scroll container).

**Comment by matiasFont** [comment]
Thanks to answer.

I've already tried those but doesn't work couse a i need to align the indexes (<index>) on the top of the viewport but i have 2 fixed elements there.

**Comment by oleggrishechkin** [comment]
manual scrolling in request/timeout doesn't work?
```
listRef.current.scrollToIndex({ index: <index>});
requestAnimationFrame(() => {
    viewportRef.current.scrollTop+= offset;
    // or with nested frame
    requestAnimationFrame(() => {
        viewportRef.current.scrollTop+= offset;
    });
});
```

scrollToIndex scroll into requestAnimationFrame, but it can be next frame or any frame after when needed element will be rendered

**Comment by oleggrishechkin** [comment]
I added `offset` in **5.1.0** version

**Comment by matiasFont** [comment]
Thank you!, ill try the new offset.

**Comment by oleggrishechkin** [comment]
Do you try new offset? Let me know if you problem fixed or not

**Comment by matiasFont** [comment]
I tried the new offset and its working, but not for me. 
I decided to implement a workaraund with `{ block: 'center' }`.

Thank You!
